openapi: 3.0.0
info:
    version: 1.0.0
    title: Foxhole frontend
servers:
  - url: http://localhost:8000/api/v1
paths:
  /users/me:
    get:
      description: Info about current user
      responses:
        200:
          description: Info about current user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
        - steam_id
        - created_at
        - updated_at
      properties:
        id:
          type: number
        name:
          type: string
        steam_id:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        faction:
          $ref: '#/components/schemas/Faction'
    Faction:
      type: object
      required:
        - id
        - name
        - slug
        - created_at
        - updated_at
      properties:
        id:
          type: number
        name:
          type: string
        slug:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    UserResponse:
        type: object
        required:
          - data
          - success
        properties:
          success:
            type: boolean
          data:
            $ref: '#/components/schemas/User'